vim \
sht/settings.py \
sht/urls.py \
portal/urls.py \
portal/views.py \
portal/templates/portal/base.html \
portal/templates/portal/index.html \
portal/templates/portal/product_lamp.html \
portal/templates/portal/contact_us.html \
portal/templates/portal/news_center.html \
portal/templates/portal/company.html \
portal/templates/portal/product_light.html \
portal/templates/portal/product_municipal.html \
portal/templates/portal/product_pip.html \
portal/templates/portal/pip_network.html \
portal/templates/portal/20180127.html \
portal/templates/portal/20180127_2.html \
portal/templates/portal/20180109.html \
portal/templates/portal/20180109_2.html \
portal/templates/portal/20180109_3.html \
portal/templates/portal/20180109_4.html \
portal/templates/portal/20171130.html \
portal/templates/portal/20171130_2.html \
portal/static/portal/css/product.css \
portal/static/portal/css/product_lamp.css \
portal/templates/portal/sht_archevement.html \
portal/templates/portal/municipal.html \
portal/templates/portal/sht_culture.html 
